[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
character-metadata = "8zcxSpeEBzyvaJzgxpLXCgEnzPe7yUsckT1GSgkYkX1v"
fake-metadata = "AzXcHxXQmuSQgfWQUSuE1af6UbD7XE7T6B297WkSZKDz"
solana_arbitrary_cpi = "5r4KrBxQEd4LzR5GYb8SWok2ZYRXZX5AinEvLoCvwLsW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
